### ISSUE TITLE
Allow skipping of adding API key for etherscan

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#118]
**Is your feature request related to a problem? Please describe.**
Getting started with MailChain is hard, lots of settings need adding. Etherscan seems to allow requests without an API key.

**Describe the solution you'd like**
If its not needed then remove the need for the API key

**Describe alternatives you've considered**
Creating an alternative for Etherscan

**Additional context**
https://etherscan.io/apis

**Comment by robdefeo** [comment]
# Tasks

- [ ] Allow skipping in `mailchain init`
- [ ] Allow an empty passphrase
- [x] Ensure that an empty API-Key will not cause problems

**Comment by tboeckmann** [comment]
According to https://etherscancom.freshdesk.com/support/solutions/articles/35000022163-i-need-an-api-key, the limit applies to users who intend to exceed limits.

Mailchain calls the api every time we check the inbox.

Other solutions might be to proxy calls via an API that masks the mailchain api_key. A user who wishes to poll Etherscan can do by adding their own api-key.

**Comment by robdefeo** [comment]
I saw similar articles. Assuming it's done on an IP address to check the limit. It's difficult to maintain a service longterm built like that. They even call this out consistently with *Note: The Ethereum Developer APIs are provided as a community service and without warranty, so please just use what you need and no more.*

**Comment by robdefeo** [comment]
closed by #122
