### ISSUE TITLE
return generic errors for aes256cbc encrypt and decrypt

### ISSUE THREAD

**Issue by robdefeo** [mailchain/mailchain#499]
**Is your feature request related to a problem? Please describe.**
Generic errors should be returned if there is a problem with encryption or decryption.

**Describe the solution you'd like**
- [ ] Ensure `Encrypt(message mc.PlainContent) (mc.EncryptedContent, error)` returns `cipher.ErrEncrypt` for all errors ref #498 
- [ ] Ensure `Decrypt(data mc.EncryptedContent) (mc.PlainContent, error)` returns `cipher.ErrDecrypt` for all errors ref #498 

**Describe alternatives you've considered**
Returning errors with details in its current state can provide additional information about the failure that should not be returned.

**Comment by developerfred** [comment]
- [x] Ensure Encrypt(message mc.PlainContent) (mc.EncryptedContent, error) returns cipher.ErrEncrypt for all errors ref #498

- [x] Ensure Decrypt(data mc.EncryptedContent) (mc.PlainContent, error) returns cipher.ErrDecrypt for all errors ref #498
